// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;


namespace Eina {
    
    
    public class Rectangle {
        
        private RectangleStruct rawStruct;
        
        public IntPtr Raw {
            get {
                System.IntPtr raw;
                raw = CreateRaw();
                Marshal.StructureToPtr(rawStruct, raw, false);
                return raw;
            }
            set {
                rawStruct = ((RectangleStruct)(Marshal.PtrToStructure(value, typeof(RectangleStruct))));
                DestroyRaw(value);
            }
        }
        
        public int X {
            get {
                int ret;
                ret = this.rawStruct.x;
                return ret;
            }
            set {
                this.rawStruct.x = value;
            }
        }
        
        public int Y {
            get {
                int ret;
                ret = this.rawStruct.y;
                return ret;
            }
            set {
                this.rawStruct.y = value;
            }
        }
        
        public int W {
            get {
                int ret;
                ret = this.rawStruct.w;
                return ret;
            }
            set {
                this.rawStruct.w = value;
            }
        }
        
        public int H {
            get {
                int ret;
                ret = this.rawStruct.h;
                return ret;
            }
            set {
                this.rawStruct.h = value;
            }
        }
        
        public static System.IntPtr CreateRaw() {
            System.IntPtr raw;
            raw = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(RectangleStruct)));
            return raw;
        }
        
        public static void DestroyRaw(System.IntPtr raw) {
            Marshal.FreeHGlobal(raw);
        }
        
        [StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
        public struct RectangleStruct {
            
            public int x;
            
            public int y;
            
            public int w;
            
            public int h;
        }
    }
    
    public class F16p16 {
        
        protected int value;
        
        public F16p16(int v) {
            value = v;
        }
        
        public int Value {
            get {
                return this.value;
            }
        }
        
        public static   implicit operator F16p16(int v) {
            return new F16p16(v);
        }
        
        public static   implicit operator System.Int32(F16p16 v) {
            return v.value;
        }
    }
    
    public class Error {
        
        protected int value;
        
        public Error(int v) {
            value = v;
        }
        
        public int Value {
            get {
                return this.value;
            }
        }
        
        public static   implicit operator Error(int v) {
            return new Error(v);
        }
        
        public static   implicit operator System.Int32(Error v) {
            return v.value;
        }
    }
}
