// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;


namespace Eina {
    
    
    public class Rectangle {
        
        protected IntPtr raw;
        
        public Rectangle() {
            raw = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(RectangleStruct)));
        }
        
        public System.IntPtr Raw {
            get {
                return this.raw;
            }
        }
        
        [StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
        public struct RectangleStruct {
            
            public int x;
            
            public int y;
            
            public int w;
            
            public int h;
        }
    }
}
